spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5432/aneeque_db
        username: postgres
    devtools:
        add-properties: true
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    mail:
        host: localhost
        port: 1025
        password: aneeque
        username: aneeque
        properties:
            mail:
                smtp:
                    ssl:
                        trust: '*'
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000
    cache:
        cache-names: aneeque
        type: redis
        redis:
            time-to-live: 600000
    redis:
        host: localhost
        port: 6379
